### ISSUE TITLE
Nice project, but it needs a different name

### ISSUE THREAD

**Issue by teyc** [vivainio/Fapper#1]
https://www.urbandictionary.com/define.php?term=fapper

**Comment by johngalambos** [comment]
I agree.  See the discussion here: https://github.com/karma-runner/karma/issues/376.  May I suggest a wordplay on the meaning of dapper itself: debonair or the like?

**Comment by vivainio** [comment]
I understand the concern, and would change the name if this turned out to be a more visible project. Currently, it's a bit of a fringe proof-of-concept  kind of thing and "it seemed fun at the time". I'll revisit this later if it turns out to be offensive or insulting (as opposed to just being a bit juvenile).

I also added a note in the README about this.

**Comment by HoraceGonzalez** [comment]
> Currently, it's a bit of a fringe proof-of-concept kind of thing and "it seemed fun at the time"

There's certainly a real world usecase for it. I've had to do the same thing myself, albeit in a one-off haphazard way. I'm sure there are others who've attempted as well. 

I would be in favor of renaming sooner rather than later when the project starts to gain traction, and it probably will.

**Comment by vivainio** [comment]
I'll think about it. Thanks for the feedback
